version: "3.8"
services:
  app:
    build: ./app
    ports:
      - '8081:80'
    depends_on:
      - api
  api:
    build: ./api
    environment:
      ADMIN_SECRET: X_CHANGE_THIS_X
      AUTH_SALT: 12
      AUTH_SECRET: foody-food
      DB_HOST: data
      DB_PORT: 7687
      DB_USER: neo4j
      DB_PASS: test
      SERVER_PORT: 80
    ports:
      - '8082:80'
    depends_on:
      - data
  data:
    image: neo4j:3.5
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      NEO4J_AUTH: neo4j/test
    volumes:
      - ./data:/data
